### ISSUE TITLE
Propose updating to Mattermost 3.6

### ISSUE THREAD

**Issue by jasonblais** [verifi-inc/mattermost#5]
Hey @kcorupe ,

Just wanted to inform you that Mattermost 3.6 release has been cut.

The new release contains security updates and several API changes - you can [view the full changelog for Mattermost 3.6 here](https://docs.mattermost.com/administration/changelog.html#release-v3-6-0) and [find download links with hash numbers here](https://pre-release.mattermost.com/core/pl/dqn4n6hy5igo7f7m3nzy919jir)

Wondering if you'd like to help update the Chef Cookbook Installer to be compatible with Mattermost 365?

If you do update, please consider tweeting about it, which we can then retweet for greater reach.

Also, feel free to join the [Mattermost Installers community channel](https://pre-release.mattermost.com/core/channels/installers-and-images) for latest news relevant for installer owners.

**Comment by jasonblais** [comment]
Hey @kcorupe !

FYI, Mattermost updated to 3.6.1 - you can find the [changelog is here](https://docs.mattermost.com/administration/changelog.html#release-v3-6-1).

Thanks, as always!

**Comment by kcorupe** [comment]
Thanks @jasonblais ... I will get this updated to the latest version. As it is that can easily be overwritten with a wrapper cookbook and should support new versions (unless there are changes to the config.json)

**Comment by jasonblais** [comment]
> As it is that can easily be overwritten with a wrapper cookbook and should support new versions (unless there are changes to the config.json)

Do you mean the cookbook will automatically support new versions of Mattermost, apart from changes to `config.json`.

**Comment by kcorupe** [comment]
Yes unless config parameters are added/removed from config.json it will work fine. Chef has a concept of wrapper cookbooks. The user includes this mattermost cookbook and then overwrites any attribute values they want (listening port/ app version/ install directory)

But its still good to keep it working with latest version so I'll still keep this updated.

**Comment by jasonblais** [comment]
Sounds good! By the way, Mattermost 3.6.2 was released - [changelog is here](https://docs.mattermost.com/administration/changelog.html#release-v3-6-1).

It includes a high severity security issue and upgrading is recommended. Blog post here with details: https://about.mattermost.com/mattermost-3-6-2/.

If you'd like to stay informed about new security updates to Mattermost, you can sign in to our [Security Bulletin mailing list](http://eepurl.com/cAl5Rv). This mailing list will receive an email about a new security release so that installers can update to that version.
